<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Product>
 */
class ProductFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $products = [
            'Laptop',
            'Smartphone',
            'Tablet',
            'Headphones',
            'Smartwatch',
            'Camera',
            'Monitor',
            'Keyboard',
            'Mouse',
            'Printer',
            'TV',
            'Refrigerator',
            'Washing Machine',
            'Dishwasher',
            'Microwave Oven',
            'Blender',
            'Coffee Maker',
            'Toaster',
            'Air Conditioner',
            'Heater',
            'Vacuum Cleaner',
            'Fan',
            'Electric Kettle',
            'Iron',
            'Hair Dryer',
            'Electric Toothbrush',
            'Shaver',
            'Razor',
            'Water Purifier',
            'Humidifier',
            'Dehumidifier',
            'Sewing Machine',
            'Electric Grill',
            'Rice Cooker',
            'Pressure Cooker',
            'Food Processor',
            'Stand Mixer',
            'Slow Cooker',
            'Juicer',
            'Electric Stove',
            'Microwave',
            'Mini Fridge',
            'Portable Speaker',
            'Smart Light Bulb',
            'Smart Thermostat',
            'Home Security Camera',
            'Smoke Detector',
            'Alarm System',
            'Smart Lock',
            'Doorbell Camera',
            'Projector',
            'Soundbar',
            'Gaming Console',
            'VR Headset',
            'Bluetooth Speaker',
            'Smart Glasses',
            'Smart Fridge',
            'Coffee Grinder',
            'Robot Vacuum',
            'Massage Chair',
            'Electric Skillet',
            'Blender Bottle',
            'Electric Shaver',
            'Portable Charger',
            'Power Bank',
            'Solar Panel',
            'Electric Bike',
            'Hoverboard',
            'Electric Scooter',
            'Smart Scale',
            'Fitness Tracker',
            'Yoga Mat',
            'Resistance Bands',
            'Dumbbells',
            'Treadmill',
            'Elliptical Machine',
            'Rowing Machine',
            'Exercise Bike',
            'Stepper',
            'Kettlebell',
            'Exercise Ball',
            'Jump Rope',
            'Boxing Gloves',
            'Gym Bag',
            'Water Bottle',
            'Yoga Block',
            'Foam Roller',
            'Massage Gun',
            'Home Gym Equipment',
            'Tennis Racket',
            'Golf Club',
            'Baseball Bat',
            'Football',
            'Soccer Ball',
            'Basketball',
            'Tennis Ball',
            'Badminton Racket',
            'Hockey Stick',
            'Baseball Glove',
            'Golf Ball',
            'Skateboard',
            'Surfboard',
            'Scooter',
            'Running Shoes',
            'Cycling Shoes',
            'CrossFit Shoes',
            'Climbing Shoes',
            'Tennis Shoes',
            'Football Cleats',
            'Baseball Cleats',
            'Soccer Cleats',
            'Golf Shoes',
            'Work Boots',
            'Casual Shoes',
            'Flip Flops',
            'High Heels',
            'Boots',
            'Sneakers',
            'Loafers',
            'Dress Shoes',
            'Sandals',
            'Slippers',
            'Wedges',
            'Ballet Flats',
            'Athletic Shoes',
            'Orthopedic Shoes',
            'Water Shoes',
            'Rain Boots',
            'Snow Boots',
            'Biking Gloves',
            'Running Shorts',
            'Track Pants',
            'Sports Bra',
            'Compression Socks',
            'Sweatband',
            'Sunglasses',
            'Sun Hat',
            'Scarf',
            'Gloves',
            'Beanie',
            'Leather Jacket',
            'Denim Jacket',
            'T-shirt',
            'Jeans',
            'Sweater',
            'Hoodie',
            'Button-up Shirt',
            'Blouse',
            'Polo Shirt',
            'Vest',
            'Overalls',
            'Chinos',
            'Cargo Pants',
            'Leggings',
            'Shorts',
            'Swimwear',
            'Bathrobe',
            'Pajamas',
            'Lingerie',
            'Socks',
            'Tights',
            'Jumpsuit',
            'Trench Coat',
            'Rain Jacket',
            'Peacoat',
            'Down Jacket',
            'Parkas',
            'Winter Coat',
            'Fleece Jacket',
            'Cardigan',
            'Suits',
            'Blazers',
            'Tuxedo',
            'Kilt',
            'Dress Shirt',
            'Cufflinks',
            'Tie',
            'Bowtie',
            'Suspenders',
            'Belt',
            'Pants Belt',
            'Wallet',
            'Clutch',
            'Handbag',
            'Backpack',
            'Laptop Bag',
            'Tote Bag',
            'Diaper Bag',
            'Duffel Bag',
            'Messenger Bag',
            'Shoulder Bag',
            'Briefcase',
            'Suitcase',
            'Travel Bag',
            'Garment Bag',
            'Hiking Backpack',
            'Camping Tent',
            'Sleeping Bag',
            'Sleeping Pad',
            'Camping Chair',
            'Camping Stove',
            'Camping Lantern',
            'Portable Cooler',
            'Fishing Rod',
            'Fishing Tackle Box',
            'Camping Hammock',
            'Backpacking Stove',
            'Portable Grill',
            'Binoculars',
            'Camping Cookware',
            'Flashlight',
            'Headlamp',
            'Camping Utensils',
            'Climbing Rope',
            'Carabiner',
            'Camping Hatchet',
            'Survival Kit',
            'Water Filter',
            'Compass',
            'Trail Map',
            'Waterproof Jacket',
            'Thermal Gloves',
            'Thermal Socks',
            'Thermal Underwear',
            'Snowshoes',
            'Ice Axe',
            'Ski Poles',
            'Skis',
            'Snowboard',
            'Ski Boots',
            'Snowboard Boots',
            'Goggles',
            'Helmet',
            'Snowsuit',
            'Mountain Boots',
            'Insulated Jacket',
            'Ski Jacket',
            'Snow Pants',
            'Ski Goggles',
            'Skating Skates',
            'Ice Fishing Gear',
            'Toboggan',
            'Ski Pass',
            'Rash Guard',
            'Beach Towel',
            'Swim Goggles',
            'Snorkel',
            'Flippers',
            'Beach Chair',
            'Sunblock',
            'Beach Bag',
            'Umbrella',
            'Beach Mat',
            'Beach Tent',
            'Sunscreen',
            'Swim Cap',
            'Water Shoes',
            'Waterproof Bag',
            'Outdoor Blanket',
            'Campfire Ring',
            'Canoe',
            'Kayak',
            'Paddle',
            'Life Jacket',
            'Stand-up Paddleboard',
            'Snorkeling Equipment',
            'Boat',
            'Raft',
            'Fishing Net',
            'Fishing Tackle',
            'Beach Umbrella',
            'Fishing Boat',
            'BBQ Grill',
            'BBQ Tools',
            'Outdoor Table',
            'Outdoor Chair',
            'Gazebo',
            'Patio Heater',
            'Swing Chair',
            'Hammock Stand',
            'Patio Umbrella',
            'Outdoor Rug',
            'Fire Pit',
            'Outdoor Heater',
            'Barbecue Cover',
            'Garden Bench',
            'Picnic Table',
            'Outdoor Lighting',
            'Planter',
            'Bird Feeder',
            'Garden Tools',
            'Lawn Mower',
            'Wheelbarrow',
            'Garden Hose',
            'Watering Can',
            'Leaf Blower',
            'Snow Blower',
            'Rake',
            'Pruning Shears',
            'Spade',
            'Shovel',
            'Trowel',
            'Garden Gloves',
            'Garden Boots',
            'Garden Apron',
            'Garden Cart',
            'Pressure Washer',
            'Chainsaw',
            'Hedge Trimmer',
            'Tractor',
            'Fertilizer',
            'Compost Bin',
            'Soil Tester',
            'Lawn Seed',
            'Lawn Fertilizer',
            'Garden Netting',
            'Garden Stakes',
            'Garden Sprayer',
            'Outdoor Storage Shed',
            'Greenhouse',
            'Rain Barrel',
            'Garden Pathway Stones',
            'Outdoor Firewood Rack',
            'Patio Furniture Set',
            'Garden Trellis',
            'Garden Arch',
            'Plant Pot',
            'Candle Lantern',
            'Wind Chimes',
            'Bird Bath',
            'Outdoor Statue',
            'Garden Fountain',
            'Firepit Table',
            'Sun Lounger',
            'Garden Umbrella Stand',
            'Picnic Basket',
            'Guitar',
            'Piano',
            'Drum Kit',
            'Violin',
            'Trumpet',
            'Saxophone',
            'Flute',
            'Clarinet',
            'Cello',
            'Accordion',
            'Harmonica',
            'Electric Guitar',
            'Acoustic Guitar',
            'Bass Guitar',
            'Electric Piano',
            'DJ Controller',
            'Microphone',
            'Amplifier',
            'Speaker System',
            'Headphones',
            'Turntable',
            'Music Stand',
            'Keyboard Stand',
            'Drumsticks',
            'Metronome',
            'Guitar Pick',
            'Guitar Strap',
            'Music Sheet',
            'Music Box',
            'Sheet Music Holder',
            'Electric Drum Kit',
            'Drum Mat',
            'Tuning Fork',
            'Piano Bench',
            'Guitar Pedal',
            'Music Instrument Tuner',
            'Tuning Pegs',
            'Recorder',
            'Ukulele',
            'Piano Tuner',
            'Percussion Instrument',
            'Karaoke Machine',
            'Microphone Stand',
            'DJ Mixer',
            'Soundproofing Foam',
            'Sound Mixer',
            'Studio Headphones',
            'Guitar Amp',
            'Guitar Capo',
            'Guitar String Set',
            'Violin Bow',
            'Trumpet Mouthpiece',
            'Saxophone Reed',
            'Cymbals',
            'Bongos',
            'Maracas',
            'Tambourine',
            'Xylophone',
            'Kettle Drums',
            'Steel Drums',
            'Chimes',
            'Percussion Blocks',
            'Banjo',
            'Mandolin',
            'Marimba',
            'Glockenspiel',
            'Zither',
            'Djembe',
            'Concertina',
            'Oboe',
            'French Horn',
            'Timpani Drum',
            'Shaker',
            'Castanets',
            'Snare Drum',
            'Cajón',
            'Tabla',
            'Dulcimer',
            'Guitar Fretboard',
            'Banjolele',
            'Flamenco Guitar',
            'Mallets',
            'Autoharp',
            'Sitar',
            'Tabla Stand',
            'Cymbal Stand',
            'Drum Pedal',
            'Double Bass',
            'Fretless Bass',
            'Lead Guitar',
            'Rugged Outdoor Speaker',
            'Guitar Case',
            'Drum Kit Stand',
            'Cymbal Pads',
            'Saxophone Neck',
            'Guitar Maintenance Kit',
            'Violin Chin Rest',
            'Guitar Tuner',
            'Digital Piano Bench',
            'Piano Pedals',
            'Hand Percussion',
            'Keyboard Stickers',
            'Carpeted Music Stand',
            'Concert Speaker',
            'Guitar Polish',
            'Electric Guitar Strings',
            'Cello Mute',
            'Woodwind Reed Case',
            'Sheet Music Holder Stand',
            'Guitar Fingerboard',
            'Percussion Mallets',
            'Keyboard Bag',
            'Metronome App',
            'Piano Practice Pad',
            'Electric Guitar Pedal',
            'Acoustic Drum Kit',
            'Violin Stand',
            'Woodwind Music Stand',
            'Guitar Tuning Peg',
            'Guitar Wall Hanger',
            'Piano Key Stickers',
            'Concert Band Kit',
            'Violin Fingerboard',
            'Tuning Peg Winder',
            'Guitar Strap Locks',
            'Acoustic Guitar Case',
            'Guitar String Winder',
            'Drum Brush',
            'Acoustic Pickup',
            'Electric Pickup',
            'Guitar Amplifier Head',
            'Keyboard Pedal',
            'Soundproof Guitar Room',
            'Electric Bass Guitar',
            'Cello Case',
            'String Quartet',
            'Piano Repair Kit',
            'Timpani Heads',
            'Snare Drum Heads',
            'Violin Case',
            'Bass Drum Pedal',
            'Drumstick Holder',
            'Concert Horn',
            'Piano Tuning Hammer',
            'Trumpet Mute',
            'Concert Drum',
            'Digital Drums',
            'Electric Drum Head',
            'Saxophone Stand',
            'Tuning App',
            'Saxophone Key',
            'Guitar Cleaning Cloth',
            'Guitar String Lubricant',
            'Drumstick Bag',
            'Woodwind Mouthpiece',
            'Tuba Case',
            'Band Instrument Case',
            'Keytar',
            'Clarinet Reed Case',
            'Flute Cleaning Rod',
            'Choral Sheet Music',
            'Brass Mouthpiece',
            'Snare Drum Stand',
            'Electric Violin',
            'Bass Guitar Amp',
            'Recorder Holder',
            'Orchestra Music Stand',
            'Flute Headjoint',
            'Violin Strings',
            'Drum Kit Heads',
            'Drum Stick Set',
            'Jazz Guitar',
            'Brass Horn',
            'Harmonica Case',
            'Jazz Trumpet',
            'Guitar Tonewood',
            'Saxophone Case',
            'Tuning Stick',
            'Drum Mat Case',
            'Violin Shoulder Rest',
            'Brass Drumsticks',
            'Electric Keyboard',
            'Djembe Stand',
            'Bongo Drum',
            'Karaoke System',
            'Guitar Fingerboard Cleaner',
            'Electric Guitar Amp Stand',
            'Flute Cork Grease',
            'Drum Kit Drumsticks',
            'Saxophone Neck Strap',
            'Concert Instrument Stand',
            'Alto Saxophone',
            'Drum Kit Kick Pedal',
            'Marching Band Drum',
            'Drumstick Holder Stand',
            'Snare Drum Wire',
            'Guitar Tone',
            'Jazz Bass Guitar',
            'Jazz Drum Kit'
        ];

        return [
            'name' => $products[fake()->numberBetween(0, count($products))],
            'price' => fake()->numberBetween(500, 1000),
            'stock' => fake()->numberBetween(500, 1000),
            'image' => 'https://picsum.photos/400/800',
        ];
    }
}
